### ISSUE TITLE
Skins should be optional

### ISSUE THREAD

**Issue by jjeising** [polimediaupv/paella#170]
It should be possible to completely disable the skin loading (e.g. with `config.skin.default = false`). 

When using custom styles switching or loading via JavaScript may not be required. Havard has [a special plugin](https://github.com/harvard-dce/dce-paella-extensions/blob/master/vendor/plugins/edu.harvard.dce.paella.forceSpecificThemePlugin/forceSpecificTheme.js) to force a style.

**Comment by miesgre** [comment]
what do you mean to disable the skin loading? That does not apear the button on the player that allow the user to change the skin?. This can be achieved in two  ways:

1.- Disable the themeChooserPlugin in config.json
```
        "es.upv.paella.themeChooserPlugin": {
                "enabled": false
            },
```

2.- Do not create the skin.available list in config.json. If the array does not exist, the themeChooserPlugin is not activated


By the way, the harvard guys does not need that plugin. They can do this in config.json
```
    "skin": {
        "default": "cs50",
    }
```
So, the cs50 plugin is loaded and no button to change the skin is showed in the player

**Comment by jjeising** [comment]
> That does not apear the button on the player that allow the user to change the skin?

That works as expected, I've already tried this. But even then `paella.utils.skin.set` and therefor `paella.utils.styleSheeet.add` is called, which create a new link tag. If you would like to integrate the player styles in an existing page stylesheet (where there are maybe processed with `less`/`sass` and combined with other styles) the player is already styled and loading an additional stylesheet is not need.
Another aspect relates to #168: [01_utils.js:102](https://github.com/polimediaupv/paella/blob/master/src/01_utils.js#L102) uses a fixed path that cannot be adapted to an existing directory structure.

**Comment by miesgre** [comment]
Now, paella tries lo load the `dark` skin if the is no `skin` configured in the config file. 
Maybe we can modify this and do not load the `dark` theme if no skin is configured, so paella will not add a link tag.

So, If the is no `skin` section in config file, paella will not add a link tag. Adopters need to add a css link tag manually in order to show their skin.

If there is a `skin` section, paella will add the tag link automatically to load the default skin and show the button in case there are a list of available skins.

Is this reasonable for you?

**Comment by jjeising** [comment]
Yes, that sounds good.
