### ISSUE TITLE
Cannot set player position to 00:00:00

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#176]
Reproduction:
1. Go to http://paellaplayer.upv.es/
2. Start playing the video
3. Try to set the playback position to 00:00:00 by any means

Actual results:
It is not possible to set the playback position to the start of the video (00:00:00). The following steps have been tried:
- Left-click and drag on the player timeline (can be set back to 00:00:01, but not 00:00:00)
- Use 10s jump (also goes back to 00:00:01 but not 00:00:00

Expected results:
It should be possible to set the playback position to the start of the video which is 00:00:00

**Comment by miesgre** [comment]
Some time ago we had a problem making seeks to 0 instant.

So, paella checks it and avoids to seek to time 0.
You can check it at https://github.com/polimediaupv/paella/blob/master/src/04_video_container.js#L533

We don't know if this issue is already a problem because browsers have changed. You can try to modify that line and test if it works for you.

In any case we will test that for the next release.
