### ISSUE TITLE
Why video.setAttribute("playsinline",null) instead of ("playsinline","playsinline") or ("playsinline","")?

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#233]
Hi, 
This is a question about setting the video element's "playsinline" attribute with value null [1]. References [2][3] say "[For] Empty attribute syntax: ... Just the attribute name. The value is implicitly the empty string." ..."The attribute’s name is the value of attribute name, its value is the empty string.". Is there a reason that "null" was chosen over using the attribute name or empty string as the attribute value?

Thanks,
Karen

[1]  "this.video.setAttribute("playsinline",null);
[1]https://github.com/polimediaupv/paella/blob/6dc7ee8142f118968f4140dff924f5455f22c4be/src/03_video_nodes.js#L398

[2] [3] "Empty attribute syntax: ... Just the attribute name. The value is implicitly the empty string."
..."The attribute’s name is the value of attribute name, its value is the empty string."[2][3]
https://www.w3.org/TR/html/syntax.html#syntax-attr-empty

**Comment by karendolan** [comment]
I also put the question to Mozilla - https://bugzilla.mozilla.org/show_bug.cgi?id=1346281
But, the mobile OS browser interpretations are more important.

**Comment by ferserc1** [comment]
The empty attribute syntax is used only in HTML code. If you pass only one parameter to setAttribute in the JavaScript DOM API, in Safari you'll get "playsinline"="undefined", and in Chrome and Firefox you'll get an error.

But the correct way to do it is to use an empty string. I think that this is a copy/paste error, but I'm not realized in this because the code works. This attribute is used only in Safari for iOS to prevent that the video plays in fullscreen mode, and apparently in this case it doesn't matter what you put inside the playsinline attribute.

I'll fix this in the next hotfix.
