### ISSUE TITLE
Changeable Asset URL

### ISSUE THREAD

**Issue by Clemens-B** [polimediaupv/paella#285]
Hello, 
nice Player :) But i have a problem to integrate it into my website. 

The Player should be displayed within the video-template (no SPA). But if I navigate to `localhost:8080/video/1223abcxy` the assets (like config.json, etc.) could not be found. I already changed the html-head to access the root of the project like so `<script type="text/javascript" src="/javascript/paella_player.js"></script>`

But the URI in the JS-Files are still depending on the browser-URL, e.g. localhost:8080/video/1223abcxy/config/config.json

How can I make Paella Player work, if the assets are under root and the Player not?

**Comment by karendolan** [comment]
Hi @Clemens-B,
The Paella team might have a better idea, but I have 2 suggestions.
1. Manually change the hard coded fallback configUrl in the paella_player.js (see snipped below), to be to the root instead of the relative path.

2.  The paella.InitDelegate initialize() allows passing an override configUrl in the initialize() of the paella.InitDelegate. Try something like this in your index.html
` <body id="body" onload="paella.load('playerContainer',{ url:'../repository/', config:{configUrl: '/player/config/config.json'} });">`


``` 
Class ("paella.InitDelegate", {
               initParams:{
                        configUrl:'config/config.json',
                        dictionaryUrl:'localization/paella',
                        accessControl:null,
                        videoLoader:null
       },
        initialize:function(params) {
                if (params) {
                        for (var key in params) {
                                this.initParams[key] = params[key];
                        }
                }
        },
        ...
        loadConfig:function() {
                return new Promise((resolve,reject) => {
                        var configUrl = this.initParams.configUrl;
                        var params = {};
                        params.url = configUrl; 
                        ...```
