### ISSUE TITLE
In Safari for macOS 10.13, the video returns to the beginning when entering full screen

### ISSUE THREAD

**Issue by polimediaupv** [polimediaupv/paella#336]
## Steps to reproduce:
1. Open a video in Safari, macOS 10.13
2. Play video
3. Enter fullscreen
 
## Actual Behavior:

The video returns to the beginning and the video image seems to be freezed.
 
## Expected Behavior:

The video continues to play normally

**Comment by karendolan** [comment]
Is this related to "paella.player.config.player.reloadOnFullscreen"? Our site does not have player config param "reloadOnFullscreen" and we are not having this problem in Safari from macOS 10.13. But, I can duplicate this issue from a UPV test video where the paella.player.config.player.reloadOnFullscreen=true. http://paellaplayer.upv.es/demo/player/index.html?id=belmar-demo

**Comment by ferserc1** [comment]
This bug affects multi-quality streams with mp4 videos. The problem is that to change the quality of the video, it is necessary to replace the stream and wait for it to load to seek the previous position, but the browser blocks this action because it's asynchronous and is not triggered by the user.

The techniques used to implement multiple qualities with mp4 are very similar to those used by advertisers in banners with videos, so the trend I've seen in recent years is that the browser blocks these actions.

I'm afraid the only possible option is to use a real video stream, such as HLS or MPEG-DASH., or to disable the reloadOnFullscreen option.

**Comment by karendolan** [comment]
For what it's worth, we use this workaround for a similar issue with Safari in one of our custom Paella plugins:
https://github.com/harvard-dce/dce-paella-extensions/blob/master/vendor/plugins/edu.harvard.dce.paella.presentationOnlyPlugin/presentationOnlyPlugin.js#L263-L281

**Comment by ferserc1** [comment]
I managed to solve the problem for macOS 10.14, using the 'emptied' event. For the tests I've done, in macOS 10.13 the problem is only partially solved: when the user change the quality, the video stops, but when the user clicks the play button again, it jumps to the instant where it left off.

Thanks for the hint
