### ISSUE TITLE
Remove Adobe Flash Support?

### ISSUE THREAD

**Issue by staubesv** [polimediaupv/paella#386]
**Is your feature request related to a problem? Please describe.**
Looking at the Paella Player code base, it seems that the Paella player still has support for Adobe Flash included (e.g. https://github.com/polimediaupv/paella/tree/develop/src/flash_player).

Maybe that could be removed?

**Describe the solution you'd like**
Remove Adobe Flash support related files from code base.

**Comment by ferserc1** [comment]
I've been trying to remove the flash drive for years.

@turro: what do you think about this?

**Comment by turro** [comment]
I'm going to ask to the list if there are people already using this. The only use case I can think about is to play RTMP in live streaming

**Comment by staubesv** [comment]
@turro Please also ask how they stream to iOS devices in case they still use Flash ;-)

**Comment by karendolan** [comment]
@ferserc1 moving away from RTMP has also been on our site's list for years, and still there. For Paella Player adopter's that never use Flash, an potentially annoying visual artifact is that the Paella Player's SWF javascript attaches a UI artifact to the loading page to test browser Flash compatibility. The loading player does this regardless of media type in the mediapackage that is retrieved shortly after. This UI artifact is visible temporarily on the page before the rest of the player UI is loaded.

[EDIT] I only mention that issue because it was also our TODO list. After investigating, it looked like it would be easier to fix for free after RTMP was not longer a concern and SWF could be removed from our build.

**Comment by staubesv** [comment]
@karendolan Does this mean that you currently are using the Flash fallback of Paella for live streaming?

**Comment by karendolan** [comment]
@staubesv yes

**Comment by miesgre** [comment]
@karendolan What streaming server are you using?  Does it support HLS or mpeg-dash?
We are also doing live streaming, but with HLS.

**Comment by ferserc1** [comment]
Flash support removed on 8cc956b6
