### ISSUE TITLE
HLS Live stream freezes after 30minutes

### ISSUE THREAD

**Issue by kevin-og** [polimediaupv/paella#402]
Using Paella pre-built 6.0.3.  We are testing hls-live with 2 HLS streams that push from Akamai w/ a 30-min DVR.  When the stream reaches the 30-min mark, Paella player fails to play.  Looks like it doesn't know what to do with a stream with DVR?  How should we approach this problem?  Or is this a limitation with Paella and DVR capabilities?  TIA

Current data.json is as follows:

`{
        "metadata": {
        "duration": 887,
        "title": "HLS Multi Live Streaming Demo"
        },
        "streams": [
                {
                "sources": {
                "hls": [
                {
                        "src": "hls-i.akamaihd.net/hls/live/XXXXXX/test1/playlist.m3u8",
                        "mimetype": "video/mp4",
                        "isLiveStream": true
                }
                ]
        },
        "preview": "",
        "content":"presenter"
        },
        {
                "sources": {
                "hls": [
                {
                        "src": "https://hls-i.akamaihd.net/hls/live/XXXXXX/test2/playlist.m3u8",
                        "mimetype": "video/mp4",
                        "isLiveStream": true
                }
                ]
        },
        "preview": "",
        "content":"presentation"
        }
                ],
        "frameList": [
        ]
}
`

**Comment by ferserc1** [comment]
There are important improvements in the HLS stream management in version 6.0.4 and 6.0.5, and as you are using a previous version, I’m going to close this issue because it is probably already resolved.

If upgrading to the latest version does not solve your problem, in my experience the problem can come form the player configuration. Unfortunately, it is not possible to modify the configuration file on the 6.0.x branch. In branch 6.1.x, it is possible to modify the configuration of the HLS playback library (hls.js) from the configuration file.

**Comment by kevin-og** [comment]
Thanks @ferserc1 , how can I find the prebuilt bits for 6.0.5?  I do not see them at https://github.com/polimediaupv/paella/releases

Best
