### ISSUE TITLE
Add attachments to a video

### ISSUE THREAD

**Issue by Jose96GIT** [polimediaupv/paella#415]
Hi, I'm using Paella Player to implement a web page with videos and I noticed that there is no possibility of include any attachments in the videos that could be downloaded by the user as a complementary material. 

In my opinion, it's a good feature that can be added, so that you can attach files like pdf or powerpoints and it will make the player more interesting instead to develop LMS pages.

**Comment by karendolan** [comment]
@Jose96GIT if you are technically inclined, you can create a custom Paella plugin to extend "paella.TabBarPlugin" to support downloading attachments associated to the video. Your new tabBarPlugin will appear in that little folder icon that shows in the menu on the Paella demo videos: https://paellaplayer.upv.es/demos/single-video-16-9/

The Paella tabBarPlugin class prototype: https://github.com/polimediaupv/paella/blob/6.1.x/src/10_paella_extended_adapter.js#L28-L50

Example tabBarPlugin code: https://github.com/polimediaupv/paella-opencast/blob/6.1.x/src/main/paella-opencast/plugins/es.upv.paella.opencast.downloadsPlugin/mh_downloads.js

An *old* 3rd party prototype example code for downloading attachment PDFs: https://github.com/harvard-dce/dce-paella-extensions/blob/v1.7.5/vendor/plugins/edu.harvard.dce.paella.tabBarHandoutDownloadPlugin/tabBarHandoutDownload.js
The old prototype example depends on this construct: paella.opencast.episode.mediapackage.attachments.attachment. The current paella uses getEpisode() instead of supplying direct access.
The prototype data attachment had to be of type "attachment/notes
     "mediapackage": {
        "attachments": {
          "attachment": [
            {
              "type": "attachment/notes",
              "mimetype": "application/pdf"
              "url": "https://acme.edu/class101/L01/classHandout.pdf"
            },

**Comment by karendolan** [comment]
@Jose96GIT Alternatively, it might be simpler to use the existing VisualAnnotationPlugin to make the PDF download accessible at a relevant time in the video https://github.com/polimediaupv/paella/blob/fd289375103654cc6b8421d348ff52bd4dc81a7d/doc/adopters/plugins/es.upv.paella.visualAnnotationPlugin.md

A benefit of using the VisualAnnotationPlugin is that the viewer has to actually watch the video in order to gain access to the PDF!
