### ISSUE TITLE
Why "expandable button plugin" instead of "popup input" for volumeRangePlugin?

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#435]
Hi,

This is a question for the design decision of going to "expandable button plugin" from the former plugin "popup input", introduced between v6.1 and v6.2.

The Paella player v6.2 volumeRangePlugin has "expandable button plugin implemented" [1] which causes the volume plugin input to become visible inline directly on the control bar and pushes the other icons around when displayed. Formally,  in v6.1, the volume input displayed as a popup input above the volume control (as it still is shown in the 6.2 markup docs[2]). The volume input display also takes a while to disappear and return the control bar to its original view.

The benefits of adopting the expandable button plugin for the volumeRangePlugin are not obvious. It would help us to adopt this change if you could provide description for the motivation of the change. 

Thank you for this great player!
Best Regards,
Karen

[1]https://github.com/polimediaupv/paella/commit/290ac199bf31728bf7e5ab3817cb859668c94d51 
[2]https://github.com/polimediaupv/paella/blob/6.2.x/doc/adopters/plugins/es.upv.paella.volumeRangePlugin.md

**Comment by rubenrua** [comment]
Please check https://github.com/polimediaupv/paella/issues/318

**Comment by ferserc1** [comment]
The motivation for making this change was the ability to silence a video with a single click:

https://github.com/polimediaupv/paella/issues/318 <https://github.com/polimediaupv/paella/issues/318>

Unfolding the volume to one side (as YouTube does) makes the slider more accessible and eliminates an inconsistency problem that would be caused if we allow the volume to unfold with hover, while other popups have to unfold with a click: the inconsistency is eliminated in this way simply by making the slider not appear in the same way as a standard popup does.

In addition, the volume slider is more accessible this way, because if you use the standard PaellaPlayer popup you have to cross the playback bar with the cursor.

In order not to push plugins to the right of the volume, one option is to change the loading order of the volume so that the last one is loaded, and that way it will be to the right.

**Comment by karendolan** [comment]
Thank you for the explanation. Our site also likes YouTube consistency. YouTube has some extra strategies to avoid crowding the other control icons. 

For possible future discussion, attached are screen shots to show how YouTube avoids the issue of pushing icons around when the volume slider is visible by using the cog settings button to contain playback rate, and other controls, that Paella has as individual plugin buttons. YouTube forces a minimum window width on PC view to avoid crowding with the volume input. For mobile, small screens, YouTube moves the volume control to the right, with a popup volume slider (!), and clickable mute/unmute.

YouTube PC view, minimum width
<img width="521" alt="YouTubeVolumePCMinWidth" src="https://user-images.githubusercontent.com/1331728/64539803-24eb6700-d2ed-11e9-86d1-64dd85b029dc.png">

YouTube mobile view, volume control on far right with popup volume control, retains single click mute/unmute
<img width="536" alt="YouTubeVolumeMobileSmallWidth" src="https://user-images.githubusercontent.com/1331728/64539800-24eb6700-d2ed-11e9-8647-0bc9c63fc45c.png">

UPV Paella 6.2 volume control
<img width="766" alt="UPVPaellaVolumePC" src="https://user-images.githubusercontent.com/1331728/64539801-24eb6700-d2ed-11e9-8b1e-b7c11f033dfc.png">
