### ISSUE TITLE
VideoContainer audioPlayer should take the streamProvider.mainAudioPlayer

### ISSUE THREAD

**Issue by karendolan** [polimediaupv/paella#441]
**Describe the bug**
If the paella streamProvider.mainAudioPlayer is not the first stream in the list of stream sources, the VideoContainer audioPlayer  won't match it. The VideoContainer audioPlayer and streamProvider.mainAudioPlayer should use the same stream source.

We see this issue because we have a weird set of old events that are published with a blank audio track on the presentation and a non-blank audio on the presenter. The presentation source always seems to be at the top of the source list, so we are tagging the presenter sources with role "master" to give them a better chance of being the main audio resource.

**To Reproduce**
1. Add role: master to the stream that should be the main audio video
2. Verify the streamProvider.mainAudioPlayer takes the video that is role:master for audio

EXPECTED:  The VideoContainer audioPlayer is set to the streamProvider.mainAudioPlayer  if one exists and the the lang's match.

ACTUAL: The VideoContainer audioPlayer is only set to streamProvider.mainAudioPlayer as a last resort if all other streams have been exhausted. The streams are never exhausted because the first stream in  the list is taken as the audio player for the video container.

I have a fix brewing locally. I'll submit to this ticket if it seems to do the right thing.
This is what I'm trying...
```
+++ b/modules/engage-paella-player/vendor/paella_overrides/src/04_video_container.js
@@ -1005,19 +1005,26 @@ class VideoContainer extends paella.VideoContainerBase {
        setAudioTag(lang) {
                return new Promise((resolve) => {
                        let audioSet = false;
-                       let firstAudioPlayer = null;
                        let promises = [];
-                       this.streamProvider.players.forEach((player) => {
-                               if (!firstAudioPlayer) {
-                                       firstAudioPlayer = player;
-                               }
-
-                               if (!audioSet && player.stream.audioTag==lang) {
-                                       audioSet = true;
-                                       this._audioPlayer = player;
-                               }
-                               promises.push(player.setVolume(0));
+                       let This = this;
+                       let firstAudioPlayer = this.streamProvider.players.find((player) => {
+                         return (This.streamProvider.mainAudioPlayer === player && player.stream.audioTag==lang);
                        });
+                       if (firstAudioPlayer) {
+                                       audioSet = true;
+                                       this._audioPlayer = firstAudioPlayer;
+                       } else {
+                         this.streamProvider.players.forEach((player) => {
+                                 if (!firstAudioPlayer) {
+                                         firstAudioPlayer = player;
+                                 }
+                                 if (!audioSet && player.stream.audioTag==lang) {
+                                         audioSet = true;
+                                         this._audioPlayer = player;
+                                 }
+                                 promises.push(player.setVolume(0));
+                         });
+                       }
 
                        // NOTE: The audio only streams must define a valid audio tag
                        if (!audioSet && this.streamProvider.mainVideoPlayer) {

...
```

**Comment by ferserc1** [comment]
In the streamProvider.startVideoSync function, the reference player is specified to do the synchronization, which always matches the audio player. I think I can fix this bug in a single line of code by changing the audioPlayer of the streamProvider when starting the video synchronization. 

I think I should do some refactoring in the future, because I get the impression that I am saving duplicate information in the streamProvider (the main audio player and the synchronization reference playar are the same), but for the moment this should solve the problem.

**Comment by karendolan** [comment]
@ferserc1 I don't understand how passing the still wrongly assigned audio player into the startVideoSync() helps when there are 2 video stream sources and the first does *not* have an audio track. Your commit leaves the firstAudioPlayer assignment to the first player in the  streamProvider.players array, which may or may not have an audio track.

This pull [EDIT, realized this is an issue with a code snippet not a pull] is to let the firstAudioPlayer be associated to the first tagged preferred "master" source, instead of randomly to the first player in the streamProvider.players array.

Still assigns firstAudioPlayer to the first random player in the streamProvider.players array:
https://github.com/polimediaupv/paella/blob/86667d4e8c99bb482ef763fb1d6149056b27b511/src/04_video_container.js#L1139-L1166

**Comment by ferserc1** [comment]
I get the impression that the problem is in the documentation (or lack of it). The audio player is being assigned correctly. 

firstAudioPlayer is assigned to the first audio player, and if there is none, to the first video player. But this property is only for compatibility reasons. The audio can be set in two modes:
- Compatibility with Paella Player 5: the firstAudioPlayer property.
- New mode: any stream can be used, but the audioTag must be configured correctly. If a video has no audio track, it should never have audioTag. This mode is also used when we only have an audio stream and a list of images.

The audioTag can be the language, but it can also be any other label. To define the default audioTag, you can use the defaultAudioTag property in the configuration file.

Here are two examples of videos with audio tracks:

repository_test/repository/multi-lang-audio/data.json
```
{
	"metadata": {
		"duration": 229,
		"title": "La competencia de la iniciativa"
	},
	"streams": [
		{
			"sources": {
				"mp4": [
					{
						"src": "https://repository.paellaplayer.upv.es/multi-lang-audio/presenter.mp4",
						"mimetype": "video/mp4",
						"res": {
							"w": "1920",
							"h": "1080"
						}
					}
				]
			},
			"preview": "",
			"type":"video",
			"content": "presenter"
		},
		{
			"sources": {
				"audio": [
					{
						"src": "https://repository.paellaplayer.upv.es/multi-lang-audio/audio-es.m4a"
					}
				]
			},
			"preview":"",
			"type":"audio",
			"audioTag":"es"
		},
        {
			"sources": {
				"audio": [
					{
						"src": "https://repository.paellaplayer.upv.es/multi-lang-audio/audio-en.m4a"
					}
				]
			},
			"preview":"",
			"type":"audio",
			"audioTag":"en"
		}
	]
}
```

repository_test/repository/dual-video-audio/data.json
```
{
	"metadata": {
		"duration": 909.13,
		"title": "Belmar 15 minutes (multiresolution)"
		]
	},
	"streams": [
		{
			"sources": {
				"mp4": [
					{
						"src": "https://repository.paellaplayer.upv.es/dual-video-audio/media/720-presenter-noaudio.mp4",
						"mimetype": "video/mp4",
						"res": {
							"w": "1280",
							"h": "720"
						}
					}
				]
			},
			"preview": "https://repository.paellaplayer.upv.es/dual-video-audio/preview/presenter_cut.jpg",
			"type":"video",
			"content":"presenter"
		},
		{
			"sources": {
				"mp4": [
					{
						"src": "https://repository.paellaplayer.upv.es/dual-video-audio/media/720-presentation.mp4",
						"mimetype": "video/mp4",
						"res": {
							"w": "962",
							"h": "720"
						}
					}
				],
				"image": [
					{
						"mimetype": "image/jpeg",
						"frames": [
							...
						],
						"count": 4,
						"duration": 909,
						"res": {
							"w": 1280,
							"h": 720
						}
					}
				]
			},
			"preview": "https://repository.paellaplayer.upv.es/dual-video-audio/preview/presentation_cut.jpg",
			"type":"video",
			"content":"presentation"
		},
		{
			"sources": {
				"audio": [
					{
						"src": "https://repository.paellaplayer.upv.es/dual-video-audio/media/presenter-audio.m4a"
					}
				]
			},
			"preview":"",
			"type":"audio",
			"audioTag":"es"
		}
	]
}
```

**Comment by karendolan** [comment]
> firstAudioPlayer is assigned to the first audio player, and if there is none, to the first video player. But this property is only for compatibility reasons. The audio can be set in two modes:...

@ferserc1 Per your comment, the concern if for the first audio player fallback to not be the first video player but, instead, as an extra feature, to be the first video player that is tagged as the master video player. *Then* fallback to whatever player exists that was not initially tagged as the initial master or preferred initial video.

Alternatively, please just say that the "streamProvider.players array" ordering must always be manually pre-forced to align with the Paella player config to insert the initial master video always to the front of the array prior to videoContainer initialization if that is the preferred audio player fallback.

Aside: Our goal is to have the main audio player to be the same as the master primary preferred video when the player is initialized. Our master video is not always the first the in source array, sometimes the secondary video comes in first and becomes the default primary audio player which is bad for us.

AFTER Re-READING your last comment, I see you are suggesting assigning something like audioTag=en to the master video data, so that it will always win as the primary audio track, regardless of the ordering of the streamProvider.players array.

Last Comment before digging into the code to insert the audioTag assignment for legacy events. I just want to confirm that adding the audioTag will enable the VideoContainer audioPlayer to be the same track as the streamProvider.mainAudioPlayer track? And that not having the audioTag will always put them in danger of being assigned from different players?

**Comment by ferserc1** [comment]
As I have already commented, the documentation is much further behind than I would like it to be. Assigning the audioTag is a mandatory requirement from version 5.1 if you want to use the multi stream audio system. If it hasn't been included in the breaking changes list it's because there wasn't really official support for multiple audios until this version.

The mainAudioPlayer is set at the end of the setAudioTag function, and in turn, setAudioTag is called when the stream load is complete, so (except for some hidden bug) the mainAudioPlayer should always match the videoContainer audioPlayer. However, my recommendation is to use the videoContainer functions preferably over the streamProvider functions.

**Comment by karendolan** [comment]
> The mainAudioPlayer is set at the end of the setAudioTag function, and in turn, setAudioTag is called when the stream load is complete, so (except for some hidden bug) the mainAudioPlayer should always match the videoContainer audioPlayer. However, my recommendation is to use the videoContainer functions preferably over the streamProvider functions.

@ferserc1 The scenario: all of the streamProvider players have an audioTag=en, because they all contain en audio. The setAudioTag() "players.forEach()" loop still looks like it will take the first player it finds in the players array with audioTag=en and toggles the audioSet boolean. Am I seeing that wrong?
https://github.com/polimediaupv/paella/blob/877805282b020ae2d74804743a3b248a32924eab/src/04_video_container.js#L1186-L1196

My semi-ultimate goal is to make the primary video, which has an audioTag=en, to always be the default mainAudioPlayer, regardless if the other players known in the streamProvider have an audioTag=en. Are you saying that in order to do this, I need to strip the audioTag=en from the secondary videos. i.e. the ones that might be at the front of the streamProvider player's array?

[EDIT: removing the ultimate goal from this discussion to prevent confusion]

**Comment by ferserc1** [comment]
The problem here is that the audioTag must be a unique identifier. In the UPV we have tried to use several audio tracks in Spanish, one for each video, but each of them corresponded to a different audio source, and in that case we tag each audioTag that way (main microphone, audio backup, etc.). Again, I apologize for not having the documentation ready yet, but I'm still trying to resolve issues with iOS 13 and iPadOS 13 related to the use of multiple audio sources, so there are certain parts of the API that are still not clear that they can be implemented..

And speaking of this, I don't know if you have been able to make any discovery in that sense, but at the moment I think it is not possible to have more than one stream with audio, since the APIs of iPadOS 13 prevent any control over the audio by javascript. In fact, it is not even possible to mute the videos, and the result when loading a video in which there are several audio streams is that all the tracks are heard simultaneously, slightly desicronized: the effect is as if the audio has a very strong echo effect.

**Comment by karendolan** [comment]
> The problem here is that the audioTag must be a unique identifier. In the UPV we have tried to use several audio tracks in Spanish, one for each video, but each of them corresponded to a different audio source, and in that case we tag each audioTag that way (main microphone, audio backup, etc.).

Thank you! Our site sums the audio and places the same audio track on all the videos of the event. This is a different scenario from you. We need the audio of the visible video to be used in order to pause the other videos to lower bandwidth and keep visible video tightly synched with the audio. I will test adding unique language tags for each video to see if the main audio track can be toggled more easily with the existing Paella 6x code.

> ... the APIs of iPadOS 13 prevent any control over the audio by javascript. In fact, it is not even possible to mute the videos, and the result when loading a video in which there are several audio streams is that all the tracks are heard simultaneously, slightly desicronized: the effect is as if the audio has a very strong echo effect.

Have you tried grouping audio and video tracks into HTMLMediaElement, HTMLVideoElement, HTMLAudioElement objects? I tested synchronizing multiple playing videos for Safari using the HTMLMediaElement.mediaGroup. It worked great, *except* that video state could only be retrieved through the group controller. The individual video elements can not provide correct information on their state, for example, if they were playing or paused. Only the controller knew and could provide  state of the videos it controlled. It was too complex to query the controller for Safari and the individual videos for the other browsers. Other browsers have support for those objects, so It might be worth looking into. https://developer.apple.com/documentation/webkitjs
This link shows audio tracks added and removed from an HTMLAudioElement controller.  https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio

[EDIT] mediaGroup is not supported by FireFox or Chrome per this https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/mediaGroup. I added videos to a master controller by adding the mediagroup attribute when creating the video element. I retrieved the controller by asking the video element for its controller. If it didn't respond with its controller, the mediagroup was not supported in that browser, and commands had to go on the video directly.
https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/Using_HTML5_Audio_Video/ControllingMediaWithJavaScript/ControllingMediaWithJavaScript.html

[Another NOTE] On Stackoverflow somewhere I read that its safer to toggle the src of a playing video object in order to change video and audio rather than moving between multiple video objects.  But I did not try test this.
