### ISSUE TITLE
How to reload an hls stream.

### ISSUE THREAD

**Issue by theodortruffer** [polimediaupv/paella#451]
Hello there

We're using the paella player in our Opencast-Plugin for ILIAS LMS, where I'm currently trying to integrate Live-Streams via HLS from Opencast. 

Now my problem: when the network connection is lost during a live stream (e.g. by turning off wifi) the paella video player will stop playing the stream (obviously), but when the connection is restored, it won't restart the stream automatically. The player is just frozen for a while and then black.

Now my question: Is it possible to reload an HLS stream manually (i.e. via JS/Jquery)?  
And (less importantly): Is is possible to check if a stream is still playing (the paella.player.playing() function is always true, since it wasn't paused)?

What I tried already:
- Reset Video src: $('#video_1').attr('src', $('#video_1').attr('src'));
- Reload Video: $('#video_1').get(0).load()
- Reload Paella player (this adds additional videos instead of reload the existing): paella.player.loadVideo()

I found some solutions on how to do this in HLS.js, but I couldn't find the reference to the hls object via the paella player. Is there a way to access this object?

Thanks in advance
Theo

**Comment by turro** [comment]
Hi Theo

There is no way to access that object,, because it was created inside a plugin. What you can do is to modify plugins/es.upv.paella.hlsPlayer/hls-player.js  to have access to the hls object.

Also there is direct access to the hls parameters in the config.json file

Finally, paella.player.playing() is always true, because up to now the hls player don't tells anything to paella. the plugin should modify that. 

Hope this helps.

Carlos

**Comment by theodortruffer** [comment]
Hey Carlos

Thanks for your help. I guess modifying the plugin would be a way, but I'd like to avoid changing the player's code (to be able to update it easily via npm).

I've found another way to reload a player - not a very elegant one, but it works in my case:
1. empty the <div> with the player
2. delete the _paella_ js-variable
3. reload the whole script (by adding a new <script> tag)

.. so kind of brutally forcing a reload of everything.

To check if a stream is still playing, I send requests to fetch the HLS-Playlist and check if it contains any streams.

I'd be happy to hear any smoother methods for this. :) Otherwise, feel free to close this question.

Thanks,
Theo

**Comment by karendolan** [comment]
HI @theodortruffer, we are not using this plugin in production, because we changed live streaming strategy. But, here is an example plugin of brute force swap and reload of an HLS stream in Paella v6.4.3  https://github.com/harvard-dce/dce-paella-extensions/blob/master/vendor/plugins/edu.harvard.dce.paella.singleVideoToggle/singleVideoToggle.js
