### ISSUE TITLE
 Player fills RAM, and crashes the Chrome browser

### ISSUE THREAD

**Issue by aliyevTU** [polimediaupv/paella#476]
# Description
It came into our attention that, when videos are being played by Paella Player on Chrome, Paella Player fills the RAM to the full and crashes the web browser.

# To Reproduce
1)Clear RAM
2)Open a double stream high-quality OC video with Paella Player on Chrome browser and max 4GB of RAM on system
3)Let it play, in 15-20 minutes browser will crash

# Environment Information
 - OS: Win 7
 - RAM: Max 4GB
 - Browser: Chrome 
 - Browser Version: Latest
 - Paella version: OC 7.4.0 version of PP

**Comment by karendolan** [comment]
@aliyevTU our site also has 2 recent separate student reports, both on Windows10 Chrome78, with the same Chrome "Not enough memory" issue after the upgrade to UPV Paella v6x. I don't know how much RAM is on their systems. They did not report this issue with the same system in the UPV Paella v5x [we are currently asking them to test with link to a Paella v5 version to see if it's specific to Chrome78 or the upgrade]. The Chrome78 came out Oct 22. We released the Paella 6x upgrade Nov 22.

Students are not reporting issues from other OS or browsers. One of the affected students is able to play videos without issue using Android Samsung A5 and the Canvas mobile app's embedded browser.

I thought it might have been the Chrome78, Win10, Symantec issue (https://www.symantec.com/connect/forums/chrome-78-update-symantec-endpoint-protection-issue). But, one of the affected students said they use Window Defender not Symatec.

**Comment by karendolan** [comment]
Not sure if this helps, but possible leads from the Chrome bug lists. One site said they made their canvas opacity 0.001 instead of hidden in order to avoid a Chrome-Windows issue with garbage collecting orphaned cache.

Dec 3, titled: "Issue 1030456: 1 GB GPU Process (700MB bloat?)". (Chrome~80 beta) Response: "We do see more OUT-OF-MEM crashes on GPU process since M77.. If you are able to repro and grab us a trace, we might have a better understanding of what's going on." https://bugs.chromium.org/p/chromium/issues/detail?id=1030456

Nov 18: Win10, Chrome78: "Issue 1026055: Chrome consumes all memory when drawing html canvas and then rendering starts to fail" (Reporter says Chrome80 beta does not have the issue)
https://bugs.chromium.org/p/chromium/issues/detail?id=1026055

Dec 4, 2019, 12:20 AM EST (9 hours ago)" Still seeing 580,005 crashes from 190,716 clients so far on latest Stable - 78.0.3904.108 on Windows OS. This crash is ranked as #5 in 'Renderer' Stable crashes. Note: Crashes came down in M77 builds. However, crashes started to spike from M78 builds."
https://bugs.chromium.org/p/chromium/issues/detail?id=968683

**Comment by turro** [comment]
That could be an explanation, since paella 6.3 uses a canvas, and paella 5.x not

**Comment by karendolan** [comment]
Ah, I'm going to try adding a visibility check in the drawTimeMarks() on the playback bar's canvas element before the hidden canvas element is adjusted on each timeupdate. In case that is the smoking hidden canvas.

**Comment by karendolan** [comment]
@turro and @aliyevTU, Good news! Chrome 79 was released as the latest stable version 2 days ago. One of our students regularly experiencing the memory issue in Chrome 78 reported that he has not experienced the problem since upgrading to Chrome 79. 

FYI -  I tested preventing canvas element writes on objects that are not visible when its parent is opaque. But, it had no affect on the memory. I could not determine where a memory leak might be  occurring. The Chrome version 79 contains hundreds of features and bug fixes over Chrome 78, a lot of them are to reduce memory bloat.

**Comment by turro** [comment]
Great to know!. Thanks, @karendolan !

**Comment by aliyevTU** [comment]
@karendolan @turro Tested latest Chrome update, it did fix the RAM issue. Thanks!

**Comment by ferserc1** [comment]
This is a bug in the web browser, which has already been corrected
