### ISSUE TITLE
Question about es.upv.paella.playButtonOnScreenPlugin option

### ISSUE THREAD

**Issue by KatrinIhler** [polimediaupv/paella#557]
Hi,
I've got a quick question about the config option "es.upv.paella.playButtonOnScreenPlugin". Someone suggested to me that I could disable it and then the play button would only be shown at the beginning, but not when someone pauses the video in between. And I can actually observe this behavior in a paella player (version 2.2.4) that's integrated in Opencast as the engage player. However, when setting this option to false in a standalone paella player (version 6.3.2), the play button is _never_ shown. So now I'm wondering, which is the intended behavior? Any idea why it behaves differently?

**Comment by ferserc1** [comment]
This is a new feature to be implemented (see issue #541). Currently this plugin can only be activated or deactivated.

**Comment by KatrinIhler** [comment]
But how is it possible that it's already working for some people? See for example https://lernfunk.de/#/recordings/7c896164-a84d-4c2f-9ae3-a23a54cfb2db

**Comment by ferserc1** [comment]
they're using the lazy load. This method works automatically as long as the browser supports it and a thumbnail image is provided in the video manifest in the metadata section:
```
"metadata": {
    "duration": 909.13,
    "title": "Belmar 15 minutes (multiresolution)",
    "preview": "preview.jpg"
},
```
To work, the browser must support automatic video playback, that is, the browser must allow video to be played without user interaction. With lazy load, only the minimum resources are loaded so that the preview image of the metadata section can be displayed, which is very useful when there are several videos embedded in a page.

If one of these conditions is not met, lazy load will not be used, and the player will be loaded directly. In that case you will not see the play icon if the playButtonOnScreenPlugin is not enabled.

The feature detailed in issue #541 will allow this behavior without the need for lazy load.

**Comment by KatrinIhler** [comment]
Oh, interesting! We're also using the lazyload, but it seems we're missing the preview image in the metadata. Maybe we'll go that route until the new feature is there.
Thank you very much for your help! :)
