### ISSUE TITLE
HLS streams cannot be displayed on iPhones iOS 14.4.1

### ISSUE THREAD

**Issue by annasaxer** [polimediaupv/paella#692]
On demand HLS videos cannot be displayed on iPhones (tested with iOS 14.4.1): on the iPhone SE it is just loading the whole time and on iPhone 12 it is not displayed at all. 

Paella version 6.2.7

**Comment by ferserc1** [comment]
I have not been able to reproduce the error. I would appreciate if you could leave a link to the stream that gives problems.

However, please note that the playback of m3u8 streams on iOS for iPhone is done natively (it is the Safari browser itself that is responsible for processing the stream). For all other platforms, including iOS for iPadOS 13 or higher, HLS stream playback is done via the [hls.js](https://github.com/video-dev/hls.js/) library, and in those cases it is possible to configure some player parameters.

For the case of native HLS playback (iOS for iPhone), the only thing Paella Player does is to place a tag `<video>` with the `src` attribute set to the URL of the stream, the rest is done by the browser and it is impossible to configure any parameter, so in these cases, and in our experience, the problem is usually in a bad configuration of the m3u8 playlist.

The following paragraph is extracted from the hls.js documentation:

> **Please note:** iOS Safari on iPhone does not support the MediaSource API. This includes all browsers on iOS as well as apps using UIWebView and WKWebView.

> Safari browsers (iOS, iPadOS, and macOS) have built-in HLS support through the plain video "tag" source URL. See the example below (Getting Started) to run appropriate feature detection and choose between using Hls.js or natively built-in HLS support.

> When a platform has neither MediaSource nor native HLS support, the browser cannot play HLS.

> Keep in mind that if the intention is to support HLS on multiple platforms, beyond those compatible with hls.js, the HLS streams need to strictly follow the specifications of RFC8216, especially if apps, smart TVs, and set-top boxes are to be supported.


I suggest you check that the stream you cannot play is correctly configured, following the RFC8216 specifications.

**Comment by annasaxer** [comment]
We also have the problem with on demand streams from opencast, that are delivered via wowza. You can test with one of the videos from the opencast summit: https://lms.uibk.ac.at/auth/RepositoryEntry/4784259339/CourseNode/102613374380600
I embedded the videos via LTI, because otherwise you cannot watch the video in our setting - I hope that is OK.

- iPhone SE, iOS 14.5: white screen, without any preview
- iPhone 12, iOS 14.6: loading-sign

**Comment by ferserc1** [comment]
As I have already commented in the previous answer, any problem with HLS on iOS platform is related to the encoding or the way of serving the stream with wowza, because on iOS the playback is native, and the m3u8 stream is passed directly to the browser.

Please, refer to the [Wowza documentation on iOS platform](https://www.wowza.com/docs/apple-hls) to check that all the settings are correct
